services:
  create-flow-demo:
    image: process
    environment:
      KAFKA_BOOTSTRAP: "kafka1.projekt.home"
      MONGO_URI: "mongodb://192.168.0.220:27017"
      MONGO_DB: "mydb"
      FLOW_ID: "6942e29c6e3fb856f2c594e0"
