services:
  register1:
    image: register1
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: "mongodb://192.168.0.220:27017"
      MONGO_DB: "SBTG_data"
      CLICKHOUSE_HOST: "db2.projekt.home"
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: ""
